#!/bin/bash
##SBATCH --job-name=run1
##SBATCH --output=run1.out
##SBATCH --error=run1.err
#SBATCH -n 16
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g
#SBATCH -N 1
work=/home/bojin9/work/test
cd $work
hostname #  > qq
date # >> qq
module list # >> qq 2>&1
sleep 60
